version: 0.2.0-build{build}
image: Visual Studio 2017

shallow_clone: true
clone_folder: c:\dotnet-properties

configuration:
  - Debug
  - Release
platform: Any CPU

matrix:
  fast_finish: true

nuget:
  account_feed: false
  project_feed: true
  disable_publish_on_pr: true

build_script:
  - cmd: dotnet build dotnet-properties.sln

test: off

artifacts:
  - path: 'artifacts\Debug\nupkg\*.nupkg'
  - path: 'artifacts\Release\nupkg\*.nupkg'

deploy:
#- provider: GitHub
#  auth_token:
#    secure: +kq8LAyp9cUJjEdoBhOCsldBLElEjcl8M+yF4Ml4bMNqaJLqvwG7nqODNBAn+kxR
#  artifact: 'artifacts\Release\nupkg\*.nupkg'
#  on:
#    branch: master
#    configuration: Release
#    appveyor_repo_tag: true
- provider: NuGet
  api_key:
    secure: 9q2Zbd01ffZzPmr0lKCPsh2hsYGYlvVadOBDL8bJmCoIWypGoE7AXMzc7NAd0NOP
  artifact: /artifacts\\Release\\nupkg\\*\.nupkg/
  on:
    branch: master
    configuration: Release
    appveyor_repo_tag: true
- provider: NuGet
  server: https://www.myget.org/F/jp2masa/api/v2/package
  artifact: /artifacts\\Debug\\nupkg\\*\.nupkg/
  api_key:
    secure: puOcEbngEmaVMEnUL20u4mzATgvoyaTPRWGGwE98as1+8KGY3ypOKzt5OV63duwI
  on:
    branch: master
    configuration: Debug
